version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      langfuse:
        patterns:
          - "@langfuse/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
