import * as fs from "node:fs";
import * as path from "node:path";

import type { TsdownPlugin } from "tsdown";

/** Collect licenses from the modules in the output, including transitive dependencies. */
export function thirdPartyNotices(): TsdownPlugin {
  return {
    name: "third-party-notices",
    generateBundle(_options, bundle) {
      const packages = new Map<string, { name: string; version: string; notices: Set<string> }>();
      for (const chunk of Object.values(bundle)) {
        if (chunk.type !== "chunk") continue;
        for (const id of Object.keys(chunk.modules)) {
          if (!id.includes(`${path.sep}node_modules${path.sep}`) || !fs.existsSync(id)) continue;
          let dir = path.dirname(id);
          while (dir !== path.dirname(dir)) {
            const manifest = path.join(dir, "package.json");
            if (fs.existsSync(manifest)) {
              const pkg = JSON.parse(fs.readFileSync(manifest, "utf8")) as {
                name?: string;
                version?: string;
              };
              if (pkg.name && pkg.version) {
                let entry = packages.get(dir);
                if (!entry) {
                  const files = fs
                    .readdirSync(dir)
                    .filter(
                      (file) =>
                        /^(licen[cs]e|notice|copyright)([.-]|$)/i.test(file) &&
                        fs.statSync(path.join(dir, file)).isFile(),
                    )
                    .sort();
                  if (!files.some((file) => /^licen[cs]e/i.test(file)))
                    this.error(`Missing license for bundled dependency ${pkg.name}`);
                  entry = {
                    name: pkg.name,
                    version: pkg.version,
                    notices: new Set(
                      files.map(
                        (file) =>
                          `${file}\n\n${fs.readFileSync(path.join(dir, file), "utf8").trim()}`,
                      ),
                    ),
                  };
                  packages.set(dir, entry);
                }
                // Some packages (notably OpenTelemetry) put attribution only in
                // source headers, rather than in their LICENSE or NOTICE file.
                for (const [comment] of fs.readFileSync(id, "utf8").matchAll(/\/\*[\s\S]*?\*\//g)) {
                  if (/copyright|@license|SPDX-License-Identifier/i.test(comment))
                    entry.notices.add(comment);
                }
                break;
              }
            }
            dir = path.dirname(dir);
          }
        }
      }
      const entries = [...packages.values()].sort((a, b) =>
        a.name < b.name
          ? -1
          : a.name > b.name
            ? 1
            : a.version < b.version
              ? -1
              : a.version > b.version
                ? 1
                : 0,
      );
      if (!entries.length) this.error("No bundled dependency licenses found");
      this.emitFile({
        type: "asset",
        fileName: "THIRD_PARTY_NOTICES.txt",
        source:
          "Third-party software bundled with the Langfuse Cursor plugin.\nGenerated by the build; do not edit manually.\n\n" +
          entries
            .map(
              (entry) =>
                `${entry.name}@${entry.version}\n${"=".repeat(72)}\n\n${[...entry.notices].sort().join("\n\n")}\n`,
            )
            .join("\n"),
      });
    },
  };
}
